### ISSUE TITLE
Qbus states are not refreshed after restart HA

### ISSUE THREAD

**Issue by wk275** [wk275/qbTools-v2#1]
After restart of Home assistant, the Qbus states are not refreshed

**Comment by mrombouts** [comment]
I solved this by adding following automation in HA. Probably a better way to get this working is possible... Especially after adding / deleting items in qBus requires an updated list with entities that need to be queried. 

`lias: Query Qbus at startup
description: Query Qbus when MQTT reloads or HA restarts
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: event_mqtt_reloaded
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: mqtt.publish
    data:
      topic: cloudapp/QBUSMQTTGW/getState
      payload: >-
        ["UL76", "UL75", "UL74", "UL73", "UL71", "UL69", "UL67", "UL66", "UL64",
        "UL61", "UL68", "UL60", "UL79", "UL77", "UL59", "UL55", "UL53", "UL52",
        "UL23", "UL58", "UL20", "UL34", "UL18", "UL24", "UL16", "UL29", "UL31",
        "UL19", "UL4", "UL10", "UL11", "UL48", "UL17", "UL13", "UL15", "UL21",
        "UL26", "UL25", "UL2", "UL6", "UL38", "UL7", "UL65", "UL44", "UL22",
        "UL9", "UL49", "UL3", "UL27", "UL30", "UL72", "UL42", "UL8", "UL32",
        "UL70", "UL54", "UL28", "UL35", "UL33", "UL36", "UL78", "UL37", "UL12",
        "UL43", "UL39", "UL40", "UL14", "UL41", "UL5", "UL45", "UL80", "UL46",
        "UL47"]
mode: single`

**Comment by wk275** [comment]
Thanks for your reply. But with a large qbus environment and a lot of entities, manual update is no easy task. I'll go for the automation.

I'll adapt the code soon to listen to the mqtt topic homeassistant/status.
Whenever it becomes online I'll initiate the update.

**Comment by wk275** [comment]
Thanks for your reply. But with a large qbus environment and a lot of entities, manual update is no easy task. I'll go for the automation.

I'll adapt the code soon to listen to the mqtt topic homeassistant/status.
Whenever it becomes online I'll initiate the update.

**Comment by wk275** [comment]
Change will be implemented in v2.2.3

**Comment by wk275** [comment]
Solved in v2.2.3
