### ISSUE TITLE
"node-red-contrib-stackhero-influxdb-v2" does not support influx V1 anymore

### ISSUE THREAD

**Issue by wk275** [wk275/qbTools-v2#2]
nodered module "node-red-contrib-stackhero-influxdb-v2" does not support influx V1 anymore
Due to this change I'll have to discontinue the 32-bit version as well
Will be implemented in v2.2.3

**Comment by asulonn** [comment]
Is "node-red-contrib-stackhero-influxdb-v2" better than "node-red-contrib-influxdb"? They seem to work simular?

**Comment by wk275** [comment]
Don't know if the 2 modules are compatible or not.
