### ISSUE TITLE
Device name is no longer filled out

### ISSUE THREAD

**Issue by asulonn** [wk275/qbTools-v2#7]
It seems like the device name in home assitant is no longer filled out

I noticed code change in the classes function node: 
```
//Ha#2371 this.parmsHa.device_name = this.parms?.device_name ? this.parms.device_name : this.qbusCollection != undefined ? "QB " + this.parmsHa.entity_type : "MQ " + this.parmsHa.entity_type;
this.parmsHa.device_name = this.parms?.device_name ? this.parms.device_name : this.qbusCollection != undefined ? "" : "";                                                   //Ha#2371 
```

I imagen in the passed the upper commented out line was ised, and now it is the lower. But it seems like "this.parms.device_name" is not filled out anywhere. 
Meaby i'm missing something.

**Comment by wk275** [comment]
You are 100% correct. As from Home assistant version 2023.08 the friendly_name creation has been changed. It takes into account the device name now, if you like it or not. The only way to remove the device name from the friendly_name was to set it to "". 
If you rather like the previous case, all the changes are tagged by Ha#2371.  
And as you noticed. Normally, the commented line is the old statement with just below the actual change. All changes are tagged by Ha#2371.
